org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
tokenMonitorVersionCode=600005
tokenMonitorVersionName=v0.60.0
tokenMonitorUpstreamVersion=0.60.0
tokenMonitorUpstreamTag=v0.60.0
tokenMonitorUpstreamCommit=8031cf3b75c7f354db8a990a983999c69086da28
