org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
tokenMonitorVersionCode=540021
tokenMonitorVersionName=v0.54.0
tokenMonitorUpstreamVersion=0.54.0
tokenMonitorUpstreamTag=v0.54.0
tokenMonitorUpstreamCommit=fce070c789ae8b1ca59be3ce7c09fd8301d6f631
