org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
tokenMonitorVersionCode=640001
tokenMonitorVersionName=v0.64.0
tokenMonitorUpstreamVersion=0.64.0
tokenMonitorUpstreamTag=v0.64.0
tokenMonitorUpstreamCommit=9ad1ca2f6ec27e497eb38fffe7d9533aec0d3c38
